CICDAPI/Models/ErrorViewModel.cs
using System;

namespace CICDAPI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CICDAPI/Models/Game.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace CICDAPI.Models
{
    public class Game
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
    }
}

CICDAPI/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using CICDAPI.Models;
using Newtonsoft.Json;


namespace CICDAPI.Controllers
{
    [Route("api/[controller]")]
    public class GameController : Controller
    {

        /// <summary>
        ///On affiche les objets du json dans la view 
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            List<Game> data = JsonConvert.DeserializeObject<List<Game>>(System.IO.File.ReadAllText("Libs/data.json"));
            this.ViewBag.monTitre = "Nos jeux vidéos";
            
            return View(data);
        }


        /// <summary>
        /// Page 404 pour les éventuelles erreurs (pages qui ne devraient pas exister)
        /// </summary>
        /// <returns></returns>
        [HttpGet("Error404")]
        public IActionResult Error404()
        {
            return View();
        }

        
        /// <summary>
        /// Affichage la vue de create
        /// </summary>
        /// <returns></returns>
        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Méthode create - les objets sont stockés dans le path libs/data.json
        /// </summary>
        /// <param name="game"></param>
        /// <returns></returns>
        [HttpPost("Create")]
        public IActionResult Create(Game game)
        {
            List<Game> data = JsonConvert.DeserializeObject<List<Game>>(System.IO.File.ReadAllText("Libs/data.json"));
            data.Add(game);
            string serializeJson = JsonConvert.SerializeObject(data, Formatting.Indented);
            System.IO.File.WriteAllText("Libs/data.json", serializeJson);

            return RedirectToAction("Index");
        }


        /// <summary>
        /// Affichage de la vue edit si l'objet existe dans le json sinon redirige vers la page 404
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet("edit/{id}")]
        public IActionResult Edit(int id)
        {
            Game gameSelected = null;
            List<Game> data = JsonConvert.DeserializeObject<List<Game>>(System.IO.File.ReadAllText("Libs/data.json"));
            gameSelected = data.FirstOrDefault(item => item.Id == id);

            if (gameSelected == null)
            {
                return RedirectToAction("Error404");
            }

            return View(gameSelected);
        }

        /// <summary>
        /// Méthode Edit - Les objets sont modifiés dans le path Libs/data.json
        /// </summary>
        /// <param name="id"></param>
        /// <param name="game"></param>
        /// <returns></returns>
        [HttpPost("Edit/{id}")]
        public IActionResult Edit(int id, Game game)
        {
            Game gameSelected = game;
            List<Game> data = JsonConvert.DeserializeObject<List<Game>>(System.IO.File.ReadAllText("Libs/data.json"));
            gameSelected = data.FirstOrDefault(item => item.Id == id);
            gameSelected.Name = game.Name;
            gameSelected.Genre = game.Genre;

            string serializeJson = JsonConvert.SerializeObject(data, Formatting.Indented);
            System.IO.File.WriteAllText("Libs/data.json", serializeJson);
            return RedirectToAction("Index");

        }

        /// <summary>
        /// Affichage de la vue delete si l'objet existe dans le json sinon redirige vers la page 404
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet("Delete/{id}")]
        public IActionResult Delete(int id)
        {
            Game gameSelected = null;
            List<Game> data = JsonConvert.DeserializeObject<List<Game>>(System.IO.File.ReadAllText("Libs/data.json"));
            gameSelected = data.FirstOrDefault(item => item.Id == id);

            if (gameSelected == null)
            {
                return RedirectToAction("Error404");
            }

            return View(gameSelected); 
        }

        /// <summary>
        /// Méthode Delete - Les objets sont supprimés dans le path Libs/data.json
        /// </summary>
        /// <param name="id"></param>
        /// <param name="game"></param>
        /// <returns></returns>
        [HttpPost("Delete/{id}")]
        public IActionResult Delete(int id, Game game)
        {
            Game gameSelected = null;
            List<Game> data = JsonConvert.DeserializeObject<List<Game>>(System.IO.File.ReadAllText("Libs/data.json"));
            gameSelected = data.FirstOrDefault(item => item.Id == id);
            data.Remove(gameSelected); 

            string serializeJson = JsonConvert.SerializeObject(data, Formatting.Indented);
            System.IO.File.WriteAllText("Libs/data.json", serializeJson);
            return RedirectToAction("Index");

        }
    }
}

CICDAPI/Controllers/HomeController.cs
using CICDAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CICDAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CICDAPI/Views/Game/Create.cshtml
@model CICDAPI.Models.Game

@{
    ViewData["Title"] = "Création d'une fiche jeu vidéo";
}


<h1>CREATE</h1>

<h4>Ajouter une fiche de jeux</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />

            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <textarea asp-for="Genre" class="form-control" cols="80" rows="10"> </textarea>
               
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste de jeux</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CICDAPI/Views/Game/Delete.cshtml
@model CICDAPI.Models.Game

@{
    ViewData["Title"] = "Delete";
}

<h1>DELETE</h1>

<h3>Es-tu sûr de vouloir supprimer cette fiche ?</h3>
<div>
    <h4>Game</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste de jeux</a>
    </form>
</div>

CICDAPI/Views/Game/Edit.cshtml
@model CICDAPI.Models.Game

@{
    ViewData["Title"] = "View";
}

<h1>EDIT</h1>

<h4>Modifier la fiche de jeu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste de jeux</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CICDAPI/Views/Game/Error404.cshtml
@{
    ViewData["Title"] = "Error404";
}

<h3 style="text-align: center; color: red;"><span style="font-weight: bold;">Error 404 :</span> Pas de chance, l'URL que vous essayez d'accéder n'existe pas</h3>

<img class="img-fluid rounded-circle mx-auto d-block border border-danger" style="width: 20%" src="https://media.tenor.com/images/18d2a19b3707dc29e606318dfd10c9f3/tenor.gif" />

CICDAPI/Views/Game/Index.cshtml
@model List<CICDAPI.Models.Game>

@{
    ViewData["Title"] = "Liste des jeux vidéos";
}

<h1 class="text-center">@ViewBag.monTitre</h1>

<div class="row justify-content-center">
    <a class="btn btn-primary" role="button" asp-controller="Game" asp-action="Create">Ajouter un nouveau jeu</a>
</div>

<h2 class="text-center small mt-4 mb-2">Liste des jeux actuels</h2>

<div class="row">

    @foreach (var game in Model)

    {
    <div class="card border m-2" style="width: 10rem; height: 15rem ">
        <div class="card-body align-content-center">
            @game.Id - Titre : @game.Name - Genre : @game.Genre
            <a style="margin-bottom: 1rem; margin-top: 1rem;" class="btn btn-primary" role="button" asp-controller="Game" asp-action="Edit" asp-route-id=@game.Id>Modifier</a>
            <a class="btn btn-danger" role="button" asp-controller="Game" asp-action="Delete" asp-route-id=@game.Id>Supprimer</a>
        </div>
    </div>
    }
</div>

CICDAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Accueil";
}

<div class="text-center">
    <h1 class="display-4">Micromania</h1>
<a style="margin-bottom: 1rem; margin-top: 1rem;" class="btn btn-secondary" role="button" asp-controller="Game" asp-action="Index">Voir les jeux</a>
<a class="btn btn-secondary" role="button" asp-controller="Game" asp-action="Create">Ajouter un jeu</a>
</div>

CICDAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Micromania - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Game" asp-action="Index">Micromania CRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li style="margin-right: 1%;" class="nav-item">
                            <span> | </span>
                        </li>

                        <li style="margin-right: 1%;" class="nav-item">
                            <a class="nav-link text-success border border-success" asp-area="" asp-controller="Game" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light border border-white" asp-area="" asp-controller="Game" asp-action="Create">Ajouter un jeu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy - Plastic Duck Method is bullsh*t
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>